#ifndef EVENT_TYPES_COMMON_HPP_
#define EVENT_TYPES_COMMON_HPP_

#define ET_SETTINGS_GET -4
#define ET_SETTINGS_SET 1
#define ET_SETTINGS_SAVE 2
#define ET_SETTINGS_LOAD 3

#define ET_WINDOW_REQUEST_CLOSE 4
#define ET_WINDOW_FOCUS_LOST 12

#define ET_INPUT_DEVICE_LOST 13

#define ET_INSTANTIATE_TIMER -1

#define ET_STAGE_ON_UPDATE 5
#define ET_STAGE_ON_SYNC 6
#define ET_STAGE_ON_FINISH 7
#define ET_STAGE_ON_DRAW 8
#define ET_STAGE_ON_PAUSE 9
#define ET_STAGE_ON_CONTINUE 10
#define ET_STAGE_ON_START 11
#define ET_STAGE_ON_CREATE 20
#define ET_STAGE_ON_UNLOAD 21

#define ET_IMGUI_TICK 14

#define ET_MOUSE_MOVE 15
#define ET_MOUSE_DOWN 16
#define ET_MOUSE_SCROLL 17

#define ET_INPUT 18

#define ET_TEXT 19

#define ET_INPUT_KEY 22

#endif

