#ifndef CANVAS_FACTORY_HPP_
#define CANVAS_FACTORY_HPP_

#include "canvas.hpp"

namespace Rhythmic
{

	enum CanvasFactoryType
	{
		CANVAS_FACTORY_MAIN,
		CANVAS_FACTORY_OPTIONS,
		CANVAS_FACTORY_SONG_SELECTION,
		CANVAS_FACTORY_SONG_PREP,
		CANVAS_FACTORY_SONG_STATS,
		CANVAS_FACTORY_SECTION_SELECTION,
		CANVAS_FACTORY_IN_GAME_HUD,
		CANVAS_FACTORY_PAUSE,
		CANVAS_FACTORY_PAUSE_OPTIONS,
		CANVAS_FACTORY_EXTRAS,
		CANVAS_FACTORY_EXTRAS_EXPERIMENTAL,
		CANVAS_FACTORY_EXTRAS_CREDITS,
		CANVAS_FACTORY_PLAYERS_SETTINGS,
		CANVAS_FACTORY_BINDINGS,
		CANVAS_FACTORY_AUTO_BINDER,
		CANVAS_FACTORY_BINDING_OPTIONS,
		CANVAS_FACTORY_ENGINE_CREATOR,
		CANVAS_FACTORY_ENGINE_CREATOR_EDITOR,
		CANVAS_FACTORY_SECRET_UNLOCK,
		CANVAS_FACTORY_CALIBRATION,
		CANVAS_FACTORY_types
	};

	class CanvasFactory
	{
	public:
		static Canvas *CreateCanvas(CanvasFactoryType type, void *canvasData = 0);
	};
}

#endif

